version: "3.8"

networks:
  network:

services:
  seed:
    image: rushprint/nats-cluster-on-docker-swarm:latest
    networks:
      - network
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    deploy:
      mode: replicated
      replicas: 1

  server:
    image: rushprint/nats-cluster-on-docker-swarm:latest
    networks:
      - network
    depends_on:
      - seed
    environment:
      - NATS_SEED_ADDRESS=nats://seed:6222
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    deploy:
      mode: replicated
      replicas: 2
